# preproduction specific configuration

environment=qualification

custom.flyway.mode=standalone

#db.user=sekoya
#db.password=sekoya
#spring.datasource.hikari.maximum-pool-size=50

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/sekoya
