# development specific configuration

configurationType=development
environment=development

custom.flyway.mode=standalone

data.path=/data/services/sekoya

# use dynamic scss rendering; switch to true to use static build-time version when available
scss.static.enabled=${SCSS_STATIC_ENABLED:false}
autoprefixer.enabled=false

api.rest.client.geocodage.url=https://data.geopf.fr/geocodage
