spec:
  inputs:
    skip-publish:
      description: Ne pas publier d'image
      default: true
      type: boolean
    skip-deploy:
      description: Ne pas déployer l'application
      default: true
      type: boolean
    deploy-reset:
      description: Reset des données applicatives lors du déploiement
      default: false
      type: boolean
    tags:
      description: "Mettre à jour les tags d'environnement (exemple: qualification production) (séparateur espace)"
      default: ""
      type: string

---

include:
 - project: kobalt/gitlab-ci
   file: igloo-standard.yml
   ref: ft-kubernetes

variables:
  DOCKER_IMAGE: igloo-containers.tools.kobalt.fr/containers/maven-igloo:3.9-eclipse-temurin-25
  DOCKER_POSTGRESQL_IMAGE: hello-world
  SKIP_igloo_delivery_preproduction: "true"
  SKIP_igloo_delivery_production: "true"
  SKIP_igloo_delivery_recette: "true"
  SKIP_igloo_delivery_qualification: "true"
  SKIP_igloo_build_war: "true"
  # TODO LAL: réactiver
  SKIP_igloo_maven_test: "true"

  SKIP_kubernetes: "false"
  SKIP_kubernetes_publish: "$[[ inputs.skip-publish ]]"
  SKIP_kubernetes_deploy: "$[[ inputs.skip-deploy ]]"
  STAGE_RESET: "$[[ inputs.deploy-reset ]]"
  KUBERNETES_REGISTRY: "nexus.tools.kobalt.fr/sekoya-registry"
  KUBERNETES_ARTIFACT_ID: "sekoya-app"
  KUBERNETES_TAGS: "$[[ inputs.tags ]]"

