name: sekoya

services:
  bdd:
    image: "igloo-containers.tools.kobalt.fr/containers/postgis-igloo:18-3.6"
    ports:
      - "127.0.0.1:2532:5432"
    volumes:
      - sekoya-bdd:/var/lib/postgresql
    environment:
      - POSTGRES_DB=sekoya
      - POSTGRES_USER=sekoya
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TZ=Europe/Paris
      - PGTZ=Europe/Paris

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "127.0.0.1:2085:8025"
      - "127.0.0.1:2025:1025"

  app-init:
    profiles:
      - app
    image: busybox:latest
    command:
    - /bin/sh
    - -c
    - chown 1002:1001 /data/services
    volumes:
      - sekoya-app:/data/services

  app:
    profiles:
      - app
    # Le dépôt est privé ; lancer le build mvn permet de construire l'image pour une disponibilité locale
    image: "nexus.tools.kobalt.fr/sekoya-registry/sekoya-app:latest"
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - sekoya-app:/data/services
    depends_on:
      app-init:
        condition: service_completed_successfully
    environment:
      SPRING_PROFILES_ACTIVE: development
      DB_HOST: bdd
      DB_PORT: 5432
      DB_USERNAME: sekoya
      DB_PASSWORD: sekoya
      # Les espaces sont nécessaires pour éviter un fusion avec BPE_PREPEND_JDK_JAVA_OPTIONS
      JDK_JAVA_OPTIONS: " -Duser.language=fr -Duser.country=FR -Duser.timezone=Europe/Paris "
      SPRING_MAIL_HOST: mailpit
      SPRING_MAIL_PORT: 1025
      # Le container ne peut pas faire tourner dartsass (tar indisponible)
      SCSS_STATIC_ENABLED: true

volumes:
  sekoya-bdd:
  sekoya-app:
