#
#	ENUM RESOURCES
#
# Use this file for resources keys related to Java enum values 

AuditAction.SIGN_IN=Connexion
AuditAction.SIGN_IN_FAIL=Echec de connexion
AuditAction.CREATE_USER=Création du compte
AuditAction.PASSWORD_RESET_REQUEST=Demande de réinitialisation de mot de passe
AuditAction.PASSWORD_CREATION_REQUEST=Demande de création de mot de passe
AuditAction.PASSWORD_UPDATE=Mise à jour de mot de passe

HistoryLogEventType.CREATE=Création
HistoryLogEventType.UPDATE=Mise à jour
HistoryLogEventType.DELETE=Suppression
HistoryLogEventType.ENABLE=Activation
HistoryLogEventType.DISABLE=Désactivation
HistoryLogEventType.SIGN_IN=Connexion
HistoryLogEventType.SIGN_IN_FAIL=Echec de connexion
HistoryLogEventType.PASSWORD_RESET_REQUEST=Demande de réinitialisation de mot de passe
HistoryLogEventType.PASSWORD_CREATION_REQUEST=Demande de création de mot de passe
HistoryLogEventType.PASSWORD_UPDATE=Mise à jour de mot de passe

Environment.development=Développement
Environment.integration=Intégration
Environment.qualification=Qualification
Environment.preproduction=Pré-production
Environment.production=Production

EnabledFilter.ENABLED_ONLY=Actifs uniquement
EnabledFilter.DISABLED_ONLY=Inactifs uniquement
EnabledFilter.ALL=Tous les éléments

SiteTypologie.TYPOLOGIE1=Typologie 1
SiteTypologie.TYPOLOGIE2=Typologie 2

ProcessusThematique.APPROVISIONNEMENTS=Approvisionnements
ProcessusThematique.INFRASTRUCTURE_EQUIPEMENTS=Infrastructures et équipements
ProcessusThematique.OPERATIONS_PROCESSUS=Opérations et processus
ProcessusThematique.ENERGIE_TELECOMS=Énergie et télécoms
ProcessusThematique.EAU=Eau
ProcessusThematique.LOGISTIQUE_TRANSPORTS=Logistique et transports
ProcessusThematique.DEMANDE=Demande

ProcessusType.FOURNISSEUR_1=Fournisseur n°1
ProcessusType.FOURNISSEUR_2=Fournisseur n°2
ProcessusType.FOURNISSEUR_3=Fournisseur n°3
ProcessusType.FOURNISSEUR_4=Fournisseur n°4
ProcessusType.INTEGRITE_BATIMENTS=Intégrité des bâtiments
ProcessusType.INTEGRITE_ENTREPOTS_STOCKS=Intégrité des entrepôts et des stocks
ProcessusType.PRATICABILITE_VOIRIE_INTERNE_ZONES_EXTERIEURES=Praticabilité de la voirie interne et zones extérieures
ProcessusType.INTEGRITE_FONCTIONNEMENT_EQUIPEMENTS_PRODUCTION=Intégrité et fonctionnement des équipements de production
ProcessusType.INTEGRITE_FONCTIONNEMENT_EQUIPEMENTS_ALIMENTATION_ELECTRIQUE=Intégrité et fonctionnement des équipements d'alimentation électrique
ProcessusType.RESEAUX_CENTRES_DONNEES_SITE=Réseaux et centres de données sur le site, autres équipements de réception/transmission de données (intégrité et fonctionnement)
ProcessusType.INTEGRITE_FONCTIONNEMENT_EQUIPEMENTS_PRODUCTION_FROID=Intégrité et fonctionnement des équipements de production de froid
ProcessusType.MAINTIEN_CONDITIONS_PRODUCTION_INTERIEUR=Maintien des conditions de production en intérieur
ProcessusType.MAINTIEN_CONDITIONS_PRODUCTION_EXTERIEUR=Maintien des conditions de production en extérieur
ProcessusType.MAINTIEN_CONDITIONS_TRAVAIL_INTERIEUR=Maintien des conditions de travail en intérieur (employés et prestataires sur site)
ProcessusType.MAINTIEN_CONDITIONS_TRAVAIL_EXTERIEUR=Maintien des conditions de travail en extérieur (employés et prestataires sur site)
ProcessusType.EXPLOITATION_RESSOURCES_NATURELLES_AGRICOLES_HALIEUTIQUES=Exploitation de ressources naturelles (agricoles ou halieutiques)
ProcessusType.EXPLOITATION_RESSOURCES_NATURELLES_TOURISTIQUES=Exploitation de ressources naturelles (touristiques)
ProcessusType.STOCKAGE_EVACUATION_EAUX_USEES=Stockage et évacuation des eaux usées
ProcessusType.STOCKAGE_EVACUATION_DECHETS=Stockage et évacuation des déchets
ProcessusType.ELECTRICITE=Électricité
ProcessusType.GAZ=Gaz
ProcessusType.RESEAU_CHALEUR_FROID=Réseau de chaleur ou de froid
ProcessusType.APPROVISIONNEMENT_STOCK_COMBUSTIBLE_SITE=Approvisionnement et stock de combustible sur site
ProcessusType.DISPONIBILITE_QUALITE_RESEAUX_TELECOMS_INTERNET=Disponibilité et qualité des réseaux télécoms et internet
ProcessusType.APPROVISIONNEMENT_EAU_PRINCIPAL_QUANTITE=Approvisionnement en eau principal - quantité d'eau disponible
ProcessusType.APPROVISIONNEMENT_EAU_PRINCIPAL_QUALITE=Approvisionnement en eau principal - qualité de l'eau disponible
ProcessusType.FLOTTE_VEHICULES_EXPLOITES_ENTREPRISE=Flotte de véhicules exploités par l'entreprise
ProcessusType.DISPONIBILITE_QUALITE_RESEAUX_TRANSPORT_MARCHANDISE=Disponibilité et qualité des réseaux de transport de marchandise (routier, ferré, fleuve, maritime, aérien) - amont/aval
ProcessusType.DEPLACEMENTS_DOMICILE_TRAVAIL_PROFESSIONNELS=Déplacements domicile-travail et professionnels (routier, ferré)
ProcessusType.PERTINENCE_OFFRE_MARCHE=Pertinence de l'offre sur le marché (niveau de demande)

ProcessusPriorite.MINEUR=Mineur
ProcessusPriorite.SECONDAIRE=Secondaire
ProcessusPriorite.IMPORTANT=Important
ProcessusPriorite.MAJEUR=Majeur
ProcessusPriorite.VITAL=Vital

AleaType.MODIFICATION_TEMPERATURES_AIR=Modification des températures de l'air
AleaType.STRESS_THERMIQUE=Stress thermique
AleaType.VARIABILITE_TEMPERATURES=Variabilité des températures
AleaType.VAGUE_CHALEUR=Vague de chaleur
AleaType.VAGUE_FROID_OU_GEL=Vague de froid ou de gel
AleaType.FEU_FORET=Feu de forêt
AleaType.TEMPETES=Tempêtes
AleaType.MODIFICATION_REGIMES_PRECIPITATIONS_PLUIE=Modification des régimes de précipitations (pluie)
AleaType.EVOLUTION_PRECIPITATIONS_NEIGEUSES_MONTAGNE=Evolution des précipitations neigeuses en montagne
AleaType.VARIATION_PRECIPITATIONS_OU_HYDROLOGIE=Variation des précipitations ou de l'hydrologie
AleaType.STRESS_HYDRIQUE=Stress hydrique
AleaType.INTRUSION_SALINE=Intrusion saline
AleaType.HAUSSE_NIVEAU_MER=Hausse du niveau de la mer
AleaType.SECHERESSE=Sécheresse
AleaType.FORTES_PRECIPITATIONS_PLUIE=Fortes précipitations (pluie)
AleaType.INONDATION_FLUVIALE=Inondation fluviale
AleaType.INONDATION_PLUVIALE=Inondation pluviale
AleaType.INONDATION_REMONTEE_NAPPE=Inondation par remontée de nappe
AleaType.INONDATION_COTIERE=Inondation côtière
AleaType.RETRAIT_GONFLEMENT_ARGILES=Retrait Gonflement des Argiles
AleaType.GLISSEMENT_TERRAIN=Glissement de terrain
AleaType.AFFAISSEMENT=Affaissement

AleaSensibilite.OPPORTUNITE=Opportunité
AleaSensibilite.TRES_FAIBLE=Très faible
AleaSensibilite.FAIBLE=Faible
AleaSensibilite.MOYENNE=Moyenne
AleaSensibilite.FORTE=Forte
AleaSensibilite.TRES_FORTE=Très forte

ImpactPotentiel.OPPORTUNITE=Opportunité
ImpactPotentiel.MINEUR=Mineur
ImpactPotentiel.SECONDAIRE=Secondaire
ImpactPotentiel.IMPORTANT=Important
ImpactPotentiel.MAJEUR=Majeur
ImpactPotentiel.CRITIQUE=Critique

CommuneTypeInsee.COMMUNE=Commune
CommuneTypeInsee.ARRONDISSEMENT_MUNICIPAL=Arrondissement
CommuneTypeInsee.COMMUNE_DELEGUEE=Déléguée
CommuneTypeInsee.COMMUNE_ASSOCIEE=Associée
CommuneTypeInsee.COMMUNE_COMER=COMER

AnnouncementType.NOTIFICATION=Notification
AnnouncementType.UNAVAILABILITY=Indisponibilité

SekoyaPermissionCategoryEnum.REFERENCE_DATA=Référentiel
SekoyaPermissionCategoryEnum.ADMINISTRATION=Administration

permission.GLOBAL_USER_READ=Consulter les utilisateurs
permission.GLOBAL_USER_WRITE=Gérer les utilisateurs
permission.GLOBAL_ANNOUNCEMENT_READ=Consulter les annonces
permission.GLOBAL_ANNOUNCEMENT_WRITE=Gérer les annonces
permission.GLOBAL_REFERENCE_DATA_READ=Consulter le référentiel
permission.GLOBAL_REFERENCE_DATA_WRITE=Gérer le référentiel
