#
#	ENUM RESOURCES
#
# Use this file for resources keys related to Java enum values 

AuditAction.SIGN_IN=Connexion
AuditAction.SIGN_IN_FAIL=Echec de connexion
AuditAction.CREATE_USER=Création du compte
AuditAction.PASSWORD_RESET_REQUEST=Demande de réinitialisation de mot de passe
AuditAction.PASSWORD_CREATION_REQUEST=Demande de création de mot de passe
AuditAction.PASSWORD_UPDATE=Mise à jour de mot de passe

HistoryLogEventType.CREATE=Création
HistoryLogEventType.UPDATE=Mise à jour
HistoryLogEventType.DELETE=Suppression
HistoryLogEventType.ENABLE=Activation
HistoryLogEventType.DISABLE=Désactivation
HistoryLogEventType.SIGN_IN=Connexion
HistoryLogEventType.SIGN_IN_FAIL=Echec de connexion
HistoryLogEventType.PASSWORD_RESET_REQUEST=Demande de réinitialisation de mot de passe
HistoryLogEventType.PASSWORD_CREATION_REQUEST=Demande de création de mot de passe
HistoryLogEventType.PASSWORD_UPDATE=Mise à jour de mot de passe

Environment.development=Développement
Environment.integration=Intégration
Environment.qualification=Qualification
Environment.preproduction=Pré-production
Environment.production=Production

EnabledFilter.ENABLED_ONLY=Actifs uniquement
EnabledFilter.DISABLED_ONLY=Inactifs uniquement
EnabledFilter.ALL=Tous les éléments

ProcessusThematique.APPROVISIONNEMENTS=Approvisionnements
ProcessusThematique.INFRASTRUCTURE_EQUIPEMENTS=Infrastructures et équipements
ProcessusThematique.OPERATIONS_PROCESSUS=Opérations et processus
ProcessusThematique.ENERGIE_TELECOMS=Énergie et télécoms
ProcessusThematique.EAU=Eau
ProcessusThematique.LOGISTIQUE_TRANSPORTS=Logistique et transports
ProcessusThematique.DEMANDE=Demande

AleaType.MODIFICATION_TEMPERATURES_AIR=Modification des températures de l'air
AleaType.STRESS_THERMIQUE=Stress thermique
AleaType.VARIABILITE_TEMPERATURES=Variabilité des températures
AleaType.VAGUE_CHALEUR=Vague de chaleur
AleaType.VAGUE_FROID_OU_GEL=Vague de froid ou de gel
AleaType.FEU_FORET=Feu de forêt
AleaType.TEMPETES=Tempêtes
AleaType.MODIFICATION_REGIMES_PRECIPITATIONS_PLUIE=Modification des régimes de précipitations (pluie)
AleaType.EVOLUTION_PRECIPITATIONS_NEIGEUSES_MONTAGNE=Evolution des précipitations neigeuses en montagne
AleaType.VARIATION_PRECIPITATIONS_OU_HYDROLOGIE=Variation des précipitations ou de l'hydrologie
AleaType.STRESS_HYDRIQUE=Stress hydrique
AleaType.INTRUSION_SALINE=Intrusion saline
AleaType.HAUSSE_NIVEAU_MER=Hausse du niveau de la mer
AleaType.SECHERESSE=Sécheresse
AleaType.FORTES_PRECIPITATIONS_PLUIE=Fortes précipitations (pluie)
AleaType.INONDATION_FLUVIALE=Inondation fluviale
AleaType.INONDATION_PLUVIALE=Inondation pluviale
AleaType.INONDATION_REMONTEE_NAPPE=Inondation par remontée de nappe
AleaType.INONDATION_COTIERE=Inondation côtière
AleaType.RETRAIT_GONFLEMENT_ARGILES=Retrait Gonflement des Argiles
AleaType.GLISSEMENT_TERRAIN=Glissement de terrain
AleaType.AFFAISSEMENT=Affaissement

CommuneTypeInsee.COMMUNE=Commune
CommuneTypeInsee.ARRONDISSEMENT_MUNICIPAL=Arrondissement
CommuneTypeInsee.COMMUNE_DELEGUEE=Déléguée
CommuneTypeInsee.COMMUNE_ASSOCIEE=Associée
CommuneTypeInsee.COMMUNE_COMER=COMER

AnnouncementType.NOTIFICATION=Notification
AnnouncementType.UNAVAILABILITY=Indisponibilité

SekoyaPermissionCategoryEnum.REFERENCE_DATA=Référentiel
SekoyaPermissionCategoryEnum.ADMINISTRATION=Administration

permission.GLOBAL_USER_READ=Consulter les utilisateurs
permission.GLOBAL_USER_WRITE=Gérer les utilisateurs
permission.GLOBAL_ANNOUNCEMENT_READ=Consulter les annonces
permission.GLOBAL_ANNOUNCEMENT_WRITE=Gérer les annonces
permission.GLOBAL_REFERENCE_DATA_READ=Consulter le référentiel
permission.GLOBAL_REFERENCE_DATA_WRITE=Gérer le référentiel
