#
#	BUSINESS RESOURCES
#
# Use this file for resources keys related to business vocabulary.
# Please mind the distinction with application messages which should lie in *ApplicationResources.properties.

business.common.enabled=Activé
business.common.enabled.true=Activé
business.common.enabled.false=Désactivé

business.common.adresse=Adresse
business.common.adresse.adresse1=Adresse 1
business.common.adresse.adresse2=Adresse 2
business.common.adresse.codePostal=Code postal
business.common.adresse.codePostal.short=CP
business.common.adresse.commune=Commune

business.common.historyEventSummary.creation=Création
business.common.historyEventSummary.creation.value=Création : ${}
business.common.historyEventSummary.modification=Modification
business.common.historyEventSummary.modification.value=Modification : ${}

#
# Organisation
#
business.organisation=Organisation
business.organisation.nom=Nom
business.organisation.chiffreAffaires=CA

#
# Site
#
business.site=Site
business.site.nom=Nom
business.site.chiffreAffaires=CA
business.site.typologie=Typologie
business.site.adresse=Adresse
business.site.localisation.coordonneesGeographiques=Coordonnées géographiques
business.site.pointGeographique=Point géographique
business.site.littoral.localisationLittoral=Localisation littoral
business.site.littoral.localisationLittoral.long=Êtes-vous localisés près d'un littoral ?
business.site.littoral.zoneSubmersible=Zone submersible
business.site.littoral.zoneSubmersible.long=Êtes-vous à moins de 2 km du littoral et < 5 m d'altitude ?
business.site.risqueBrutRcp45Annee2035=Risque brut · RCP 4.5 · 2035
business.site.risqueBrutRcp45Annee2055=Risque brut · RCP 4.5 · 2055
business.site.risqueBrutRcp85Annee2035=Risque brut · RCP 8.5 · 2035
business.site.risqueBrutRcp85Annee2055=Risque brut · RCP 8.5 · 2055


#
# Processus
#
business.processus=Processus
business.processus.site=Site
business.processus.thematique=Thématique
business.processus.type=Type
business.processus.nom=Nom
business.processus.description=Description
business.processus.priorite=Priorité
business.processus.aleas=Aléas

business.alea=Aléa
business.alea.type=Type
business.alea.sensibilite=Sensibilité
business.alea.impactPotentielBrut=Impact potentiel brut

#
# Reference data
#
business.referenceData.label=Libellé
business.referenceData.code=Code
business.referenceData.position=Position
business.referenceData.enabled=Activé
business.referenceData.enabled.state=Actif

business.referenceData.label=Libellé

business.commune=Commune
business.commune.codesPostaux=Codes postaux
business.commune.codesPostaux.short=CP
business.commune.codePostal=Code postal
business.commune.codePostal.short=CP
business.commune.codeInsee=Code INSEE
business.commune.codeInsee.short=INSEE
business.commune.typeInsee=Type INSEE
business.commune.departement=Département

business.departement=Département
business.departement.codeInsee=Code INSEE
business.departement.codeInsee.short=INSEE
business.departement.region=Région

business.region=Région
business.region.codeInsee=Code INSEE
business.region.codeInsee.short=INSEE

#
# User
#
business.user=Utilisateur
business.user.firstName=Prénom
business.user.lastName=Nom
business.user.fullName=Nom complet
business.user.username=Identifiant
business.user.name=Nom
business.user.emailAddress=Email
business.user.enabled=Activé
business.user.enabled.true=Activé
business.user.enabled.false=Désactivé
business.user.enabled.state=Actif
business.user.lastLoginDate=Dernière connexion
business.user.password=Mot de passe
business.user.oldPassword=Ancien mot de passe
business.user.newPassword=Nouveau mot de passe
business.user.roles=Rôles

business.userOrganisation.organisation=Organisation

#
# Authority
#
business.authority.name.ROLE_ADMIN=Administrateur
business.authority.name.ROLE_AUTHENTICATED=Utilisateur
business.authority.name.ROLE_ANONYMOUS=Anonyme

#
# Announcement
#
business.announcement.id=Id
business.announcement.type=Type
business.announcement.content=Contenu
business.announcement.unavailability.dates=Dates d'indisponibilité
business.announcement.unavailability.content=##### {0}\n\n\
L'application sera indisponible du **{1}** à **{2}** au **{3}** à **{4}**.
business.announcement.unavailability.content.sameDay=##### {0}\n\n\
L'application sera indisponible le **{1}** de **{2}** à **{3}**.
business.announcement.publication.dates=Dates de publication
business.announcement.publication.startDateTime=Début de publication
business.announcement.publication.endDateTime=Fin d'interruption
business.announcement.enabled=Activé
business.announcement.enabled.true=Activé
business.announcement.enabled.false=Désactivé

#
# HistoryLog
#
business.historyLog.date=Date
business.historyLog.eventType=Action
business.historyLog.subject=Auteur
business.historyLog.detail=Détail

history.difference.common.default.updated.before=
history.difference.common.default.updated.after=
history.difference.common.default.untouched.before=
history.difference.common.default.untouched.after= (non modifié)
history.difference.common.default.added.before=Ajout de « 
history.difference.common.default.added.after= »
history.difference.common.default.removed.before=Retrait de « 
history.difference.common.default.removed.after= »
history.difference.common.default.value=${current}
history.difference.common.composite.updated=Modifié.
history.difference.common.composite.untouched=Non modifié.
history.difference.common.composite.added=Ajouté.
history.difference.common.composite.removed=Retiré.

history.difference.user=Utilisateur
history.difference.user.emailAddress=Email
history.difference.user.emailAddress.value=Email
history.difference.user.enabled=Activé
history.difference.user.firstName=Prénom
history.difference.user.lastName=Nom
history.difference.user.roles=Rôles
history.difference.user.username=Identifiant
