package sekoya.back.business.alea.model.atomic;

public enum AleaType {
  MODIFICATION_TEMPERATURES_AIR,
  STRESS_THERMIQUE,
  VARIABILITE_TEMPERATURES,
  VAGUE_CHALEUR,
  VAGUE_FROID_OU_GEL,
  FEU_FORET,
  TEMPETES,
  MODIFICATION_REGIMES_PRECIPITATIONS_PLUIE,
  EVOLUTION_PRECIPITATIONS_NEIGEUSES_MONTAGNE,
  VARIATION_PRECIPITATIONS_OU_HYDROLOGIE,
  STRESS_HYDRIQUE,
  INTRUSION_SALINE,
  HAUSSE_NIVEAU_MER,
  SECHERESSE,
  FORTES_PRECIPITATIONS_PLUIE,
  INONDATION_FLUVIALE,
  INONDATION_PLUVIALE,
  INONDATION_REMONTEE_NAPPE,
  INONDATION_COTIERE,
  RETRAIT_GONFLEMENT_ARGILES,
  GLISSEMENT_TERRAIN,
  AFFAISSEMENT;
}
